version: '3'

services:

 kong-database:
   image: postgres:9.6
   container_name: kong-database
   ports:
     - 5432:5432
   environment:
     - POSTGRES_USER=kong
     - POSTGRES_DB=kong
     - POSTGRES_PASSWORD=kong
   networks:
     - kong-net
   volumes:
     - "db-data-kong-postgres:/var/lib/postgresql/data"
     - "/etc/localtime:/etc/localtime:ro"

 kong-migrations:
   image: kong:latest
   environment:
     - KONG_DATABASE=postgres
     - KONG_PG_HOST=kong-database
     - KONG_PG_PASSWORD=kong
   command: kong migrations bootstrap
   restart: on-failure
   networks:
     - kong-net
   depends_on:
     - kong-database
 kong:
   image: kong:latest
   container_name: kong
   environment:
     - KONG_DATABASE=postgres
     - KONG_PG_HOST=kong-database
     - KONG_PG_PASSWORD=kong
     - KONG_PROXY_ACCESS_LOG=/dev/stdout
     - KONG_ADMIN_ACCESS_LOG=/dev/stdout
     - KONG_PROXY_ERROR_LOG=/dev/stderr
     - KONG_ADMIN_ERROR_LOG=/dev/stderr
     - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
   restart: on-failure
   ports:
     - 8000:8000
     - 8443:8443
     - 8001:8001
     - 8444:8444
   links:
     - kong-database:kong-database
   networks:
     - kong-net
   depends_on:
     - kong-migrations
   volumes:
     - "/etc/localtime:/etc/localtime:ro"
     - "/etc/timezone:/etc/timezone:ro"

 wingman:
    build: ./server
    ports:
      - "49160:3000"
    image: wingman
    container_name: wingman
    networks: 
     - kong-net
 ocr:
    build: ./OCR
    ports:
      - "49161:5000"
    image: ocr
    container_name: OCR
    networks: 
     - kong-net

volumes:
 db-data-kong-postgres:

networks:
 kong-net:
   external: false