import {FONTS, COLORS, SHADOWS, SIZES, CATEGORIESCOLORS } from "./theme";
import { CATEGORIES, SIGNS } from "./categories";
export {FONTS, COLORS, SHADOWS, SIZES , CATEGORIES, CATEGORIESCOLORS, SIGNS};
