insert into product (description) values ('Marzipan 50/50');
insert into product (description) values ('Vanilla Beans');
insert into product (description) values ('Olive - Spread Tapenade');
insert into product (description) values ('Table Cloth 54x72 White');
insert into product (description) values ('French Kiss Vanilla');
insert into product (description) values ('Wine - Red, Pinot Noir, Chateau');
insert into product (description) values ('Pastry - Lemon Danish - Mini');
insert into product (description) values ('Boogies');
insert into product (description) values ('Sword Pick Asst');
insert into product (description) values ('Beef - Tenderlion, Center Cut');
insert into product (description) values ('Beans - Black Bean, Dry');
insert into product (description) values ('Wine - Red, Colio Cabernet');
insert into product (description) values ('Syrup - Pancake');
insert into product (description) values ('Sauce - Marinara');
insert into product (description) values ('Wine - Valpolicella Masi');
insert into product (description) values ('Tart - Lemon');
insert into product (description) values ('Turkey - Ground. Lean');
insert into product (description) values ('Pants Custom Dry Clean');
insert into product (description) values ('Turkey - Breast, Boneless Sk On');
insert into product (description) values ('Apricots Fresh');
insert into product (description) values ('Jameson Irish Whiskey');
insert into product (description) values ('Flour - Rye');
insert into product (description) values ('Water - Aquafina Vitamin');
insert into product (description) values ('Spice - Greek 1 Step');
insert into product (description) values ('Longos - Cheese Tortellini');
insert into product (description) values ('Wine - Riesling Alsace Ac 2001');
insert into product (description) values ('Dr. Pepper - 355ml');
insert into product (description) values ('Kirsch - Schloss');
insert into product (description) values ('Coffee Cup 12oz 5342cd');
insert into product (description) values ('Chervil - Fresh');
insert into product (description) values ('Tea - Jasmin Green');
insert into product (description) values ('Wine - Cousino Macul Antiguas');
insert into product (description) values ('Rambutan');
insert into product (description) values ('Beer - Moosehead');
insert into product (description) values ('Miso - Soy Bean Paste');
insert into product (description) values ('Boogies');
insert into product (description) values ('Shrimp - 16/20, Peeled Deviened');
insert into product (description) values ('Beans - Long, Chinese');
insert into product (description) values ('Coffee - French Vanilla Frothy');
insert into product (description) values ('Containter - 3oz Microwave Rect.');
insert into product (description) values ('Appetizer - Mango Chevre');
insert into product (description) values ('Mace Ground');
insert into product (description) values ('Lamb - Whole Head Off');
insert into product (description) values ('Pasta - Rotini, Colour, Dry');
insert into product (description) values ('Juice - Ocean Spray Cranberry');
insert into product (description) values ('Tray - Foam, Square 4 - S');
insert into product (description) values ('Tendrils - Baby Pea, Organic');
insert into product (description) values ('Paper - Brown Paper Mini Cups');
insert into product (description) values ('Sugar - Cubes');
insert into product (description) values ('Beans - Navy, Dry');
insert into product (description) values ('Canada Dry');
insert into product (description) values ('Soup - Campbellschix Stew');
insert into product (description) values ('Barramundi');
insert into product (description) values ('Butter - Unsalted');
insert into product (description) values ('Pepper - Green, Chili');
insert into product (description) values ('Appetizer - Crab And Brie');
insert into product (description) values ('Catfish - Fillets');
insert into product (description) values ('Muskox - French Rack');
insert into product (description) values ('Nantucket - Pomegranate Pear');
insert into product (description) values ('Dikon');
insert into product (description) values ('Rosemary - Primerba, Paste');
insert into product (description) values ('Beans - Fava Fresh');
insert into product (description) values ('Carbonated Water - Wildberry');
insert into product (description) values ('Oil - Canola');
insert into product (description) values ('Jack Daniels');
insert into product (description) values ('Basil - Seedlings Cookstown');
insert into product (description) values ('Muffin Mix - Raisin Bran');
insert into product (description) values ('Lamb - Shanks');
insert into product (description) values ('Shallots');
insert into product (description) values ('Foil - Round Foil');
insert into product (description) values ('Guinea Fowl');
insert into product (description) values ('Beer - Camerons Cream Ale');
insert into product (description) values ('Bar Energy Chocchip');
insert into product (description) values ('Eel Fresh');
insert into product (description) values ('Sauce - Vodka Blush');
insert into product (description) values ('Oysters - Smoked');
insert into product (description) values ('Beef - Inside Round');
insert into product (description) values ('Ham - Cooked Italian');
insert into product (description) values ('Bar Mix - Lime');
insert into product (description) values ('White Baguette');
insert into product (description) values ('Vaccum Bag - 14x20');
insert into product (description) values ('Tuna - Salad Premix');
insert into product (description) values ('Chips - Doritos');
insert into product (description) values ('Chicken - Wieners');
insert into product (description) values ('Smoked Paprika');
insert into product (description) values ('Sobe - Lizard Fuel');
insert into product (description) values ('Uniform Linen Charge');
insert into product (description) values ('Muffin - Carrot Individual Wrap');
insert into product (description) values ('Breakfast Quesadillas');
insert into product (description) values ('Sauce - Soya, Dark');
insert into product (description) values ('Juice - Happy Planet');
insert into product (description) values ('Turkey Tenderloin Frozen');
insert into product (description) values ('V8 Splash Strawberry Kiwi');
insert into product (description) values ('Seedlings - Clamshell');
insert into product (description) values ('Beer - Molson Excel');
insert into product (description) values ('Truffle Cups - Red');
insert into product (description) values ('Mushroom - Portebello');
insert into product (description) values ('Flax Seed');
insert into product (description) values ('Irish Cream - Butterscotch');
insert into product (description) values ('Syrup - Golden, Lyles');
insert into product (description) values ('Nantucket - Carrot Orange');
insert into product (description) values ('Split Peas - Yellow, Dry');
insert into product (description) values ('Pumpkin');
insert into product (description) values ('Oil - Margarine');
insert into product (description) values ('Onions - Cooking');
insert into product (description) values ('Beer - Guiness');
insert into product (description) values ('Cheese - Cheddar, Medium');
insert into product (description) values ('Pork - Backs - Boneless');
insert into product (description) values ('Chips Potato Swt Chilli Sour');
insert into product (description) values ('Stock - Chicken, White');
insert into product (description) values ('Wine - Touraine Azay - Le - Rideau');
insert into product (description) values ('Pasta - Canelloni, Single Serve');
insert into product (description) values ('Miso Paste White');
insert into product (description) values ('Sprite - 355 Ml');
insert into product (description) values ('Wine - Sake');
insert into product (description) values ('Compound - Mocha');
insert into product (description) values ('Lemonade - Strawberry, 591 Ml');
insert into product (description) values ('Ice Cream - Life Savers');
insert into product (description) values ('Flower - Commercial Bronze');
insert into product (description) values ('Cup - Paper 10oz 92959');
insert into product (description) values ('Tea - Decaf 1 Cup');
insert into product (description) values ('Soup - Campbells, Classic Chix');
insert into product (description) values ('Bread - Crumbs, Bulk');
insert into product (description) values ('Cabbage - Nappa');
insert into product (description) values ('Taro Root');
insert into product (description) values ('Lemon Grass');
insert into product (description) values ('Cheese - Brie, Triple Creme');
insert into product (description) values ('Juice - V8 Splash');
insert into product (description) values ('Bagel - Ched Chs Presliced');
insert into product (description) values ('Pork - Loin, Center Cut');
insert into product (description) values ('Carbonated Water - Raspberry');
insert into product (description) values ('Yeast - Fresh, Fleischman');
insert into product (description) values ('Jam - Blackberry, 20 Ml Jar');
insert into product (description) values ('Tequila - Sauza Silver');
insert into product (description) values ('Quail - Whole, Boneless');
insert into product (description) values ('Snails - Large Canned');
insert into product (description) values ('Glass Clear 8 Oz');
insert into product (description) values ('Wine - White, Riesling, Semi - Dry');
insert into product (description) values ('Pastry - Trippleberry Muffin - Mini');
insert into product (description) values ('Tea - Herbal Orange Spice');
insert into product (description) values ('Cornish Hen');
insert into product (description) values ('Fiddlehead - Frozen');
insert into product (description) values ('Ecolab - Power Fusion');
insert into product (description) values ('Wooden Mop Handle');
insert into product (description) values ('Wine - Acient Coast Caberne');
insert into product (description) values ('Wine - Beaujolais Villages');
insert into product (description) values ('Lamb Shoulder Boneless Nz');
insert into product (description) values ('Bread - Crumbs, Bulk');
insert into product (description) values ('Wine - Chenin Blanc K.w.v.');
insert into product (description) values ('Sauce - Rosee');
insert into product (description) values ('Bread - White, Sliced');
insert into product (description) values ('Kiwi Gold Zespri');
insert into product (description) values ('Chips Potato All Dressed - 43g');
insert into product (description) values ('Water Chestnut - Canned');
insert into product (description) values ('Pumpkin');
insert into product (description) values ('Ham - Proscuitto');
insert into product (description) values ('Containter - 3oz Microwave Rect.');
insert into product (description) values ('Nut - Pistachio, Shelled');
insert into product (description) values ('Appetizer - Tarragon Chicken');
insert into product (description) values ('Pastry - Apple Muffins - Mini');
insert into product (description) values ('Chicken - Ground');
insert into product (description) values ('Beer - Camerons Auburn');
insert into product (description) values ('Flower - Potmums');
insert into product (description) values ('Wine - Red, Mouton Cadet');
insert into product (description) values ('Lobster - Cooked');
insert into product (description) values ('Beef - Ground, Extra Lean, Fresh');
insert into product (description) values ('Beets - Candy Cane, Organic');
insert into product (description) values ('Chocolate - Semi Sweet');
insert into product (description) values ('Pail For Lid 1537');
insert into product (description) values ('Flavouring - Raspberry');
insert into product (description) values ('Lettuce - Romaine');
insert into product (description) values ('Pear - Packum');
insert into product (description) values ('Wine - Champagne Brut Veuve');
insert into product (description) values ('Island Oasis - Peach Daiquiri');
insert into product (description) values ('Ecolab - Hobart Upr Prewash Arm');
insert into product (description) values ('Radish - Pickled');
insert into product (description) values ('Wine - White, Pinot Grigio');
insert into product (description) values ('Chinese Foods - Chicken Wing');
insert into product (description) values ('Lettuce - Iceberg');
insert into product (description) values ('Puff Pastry - Slab');
insert into product (description) values ('Bread - Sour Sticks With Onion');
insert into product (description) values ('Nantucket - Pomegranate Pear');
insert into product (description) values ('Salt And Pepper Mix - Black');
insert into product (description) values ('Veal Inside - Provimi');
insert into product (description) values ('Bread - Pita, Mini');
insert into product (description) values ('Mince Meat - Filling');
insert into product (description) values ('Arizona - Plum Green Tea');
insert into product (description) values ('Lamb Shoulder Boneless Nz');
insert into product (description) values ('Beets - Candy Cane, Organic');
insert into product (description) values ('Oil - Truffle, Black');
insert into product (description) values ('Appetizer - Asian Shrimp Roll');
insert into product (description) values ('Lobster - Tail, 3 - 4 Oz');
insert into product (description) values ('Tuna - Sushi Grade');
insert into product (description) values ('Milk - 2% 250 Ml');
insert into product (description) values ('Cookies - Fortune');
insert into product (description) values ('Red Cod Fillets - 225g');
insert into product (description) values ('Muffin Mix - Chocolate Chip');
insert into product (description) values ('Bread - Pumpernickel');
insert into product (description) values ('Towel Multifold');
insert into product (description) values ('Syrup - Pancake');
insert into product (description) values ('Fondant - Icing');
insert into product (description) values ('Ice Cream - Super Sandwich');
insert into product (description) values ('Oil - Peanut');
insert into product (description) values ('Veal - Round, Eye Of');
insert into product (description) values ('Goat - Leg');
insert into product (description) values ('Wine - Cahors Ac 2000, Clos');
insert into product (description) values ('Sugar - Invert');
insert into product (description) values ('Lotus Rootlets - Canned');
insert into product (description) values ('Shiro Miso');
insert into product (description) values ('Flavouring Vanilla Artificial');
insert into product (description) values ('Tomatoes - Vine Ripe, Red');
insert into product (description) values ('Vermouth - Sweet, Cinzano');
insert into product (description) values ('Horseradish Root');
insert into product (description) values ('Wine - Pinot Noir Stoneleigh');
insert into product (description) values ('Curry Powder');
insert into product (description) values ('Salami - Genova');
insert into product (description) values ('Tomatoes');
insert into product (description) values ('Turkey - Ground. Lean');
insert into product (description) values ('Mussels - Frozen');
insert into product (description) values ('Currants');
insert into product (description) values ('Ecolab - Orange Frc, Cleaner');
insert into product (description) values ('Catfish - Fillets');
insert into product (description) values ('Scallops - U - 10');
insert into product (description) values ('Shrimp - 16/20, Peeled Deviened');
insert into product (description) values ('Cornflakes');
insert into product (description) values ('Coke - Diet, 355 Ml');
insert into product (description) values ('Wine - Fontanafredda Barolo');
insert into product (description) values ('Apricots Fresh');
insert into product (description) values ('Tendrils - Baby Pea, Organic');
insert into product (description) values ('Grouper - Fresh');
insert into product (description) values ('Coffee Cup 8oz 5338cd');
insert into product (description) values ('Bread Country Roll');
insert into product (description) values ('Cheese - Cheddarsliced');
insert into product (description) values ('Mix - Cocktail Strawberry Daiquiri');
insert into product (description) values ('Wine - Beringer Founders Estate');
insert into product (description) values ('Crawfish');
insert into product (description) values ('Puree - Strawberry');
insert into product (description) values ('Crab - Dungeness, Whole, live');
insert into product (description) values ('Boogies');
insert into product (description) values ('Bread - Malt');
insert into product (description) values ('Juice - Orange, 341 Ml');
insert into product (description) values ('Squid - U - 10 Thailand');
insert into product (description) values ('Cardamon Seed / Pod');
insert into product (description) values ('Island Oasis - Mango Daiquiri');
insert into product (description) values ('Wine - Chateau Bonnet');
insert into product (description) values ('Cinnamon - Ground');
insert into product (description) values ('Bag - Clear 7 Lb');
insert into product (description) values ('Pepper - Paprika, Spanish');
insert into product (description) values ('Foam Cup 6 Oz');
insert into product (description) values ('Flour - So Mix Cake White');
insert into product (description) values ('Carroway Seed');
insert into product (description) values ('Smoked Paprika');
insert into product (description) values ('Juice - Grapefruit, 341 Ml');
insert into product (description) values ('Squash - Butternut');
insert into product (description) values ('Browning Caramel Glace');
insert into product (description) values ('Wanton Wrap');
insert into product (description) values ('Cheese - Oka');
insert into product (description) values ('Kaffir Lime Leaves');
insert into product (description) values ('Bar Mix - Lime');
insert into product (description) values ('Cheese - Fontina');
insert into product (description) values ('Rhubarb');
insert into product (description) values ('Pepper - Chili Powder');
insert into product (description) values ('Catfish - Fillets');
insert into product (description) values ('Wine - Prem Select Charddonany');
insert into product (description) values ('Olives - Morracan Dired');
insert into product (description) values ('Brandy - Orange, Mc Guiness');
insert into product (description) values ('Wine - Fat Bastard Merlot');
insert into product (description) values ('Muffin - Bran Ind Wrpd');
insert into product (description) values ('Steamers White');
insert into product (description) values ('Petite Baguette');
insert into product (description) values ('Cucumber - English');
insert into product (description) values ('Onions - Pearl');
insert into product (description) values ('Wine - Delicato Merlot');
insert into product (description) values ('Veal - Inside Round / Top, Lean');
insert into product (description) values ('Lettuce - Belgian Endive');
insert into product (description) values ('Wine - Jaboulet Cotes Du Rhone');
insert into product (description) values ('Capers - Pickled');
insert into product (description) values ('Turkey - Breast, Boneless Sk On');
insert into product (description) values ('Snapple - Mango Maddness');
insert into product (description) values ('Wine - Magnotta, White');
insert into product (description) values ('Puree - Strawberry');
insert into product (description) values ('Asparagus - White, Canned');
insert into product (description) values ('Wine - Red, Gallo, Merlot');
insert into product (description) values ('Numi - Assorted Teas');
insert into product (description) values ('Godiva White Chocolate');
insert into product (description) values ('Carbonated Water - Orange');
insert into product (description) values ('Beer - Fruli');
insert into product (description) values ('Venison - Ground');
insert into product (description) values ('Spinach - Packaged');
insert into product (description) values ('Cabbage - Nappa');
insert into product (description) values ('Cake - French Pear Tart');
insert into product (description) values ('Bacardi Breezer - Strawberry');
insert into product (description) values ('Carbonated Water - Wildberry');
insert into product (description) values ('Sandwich Wrap');
insert into product (description) values ('Cookie Trail Mix');
insert into product (description) values ('Cattail Hearts');
insert into product (description) values ('Mix - Cocktail Ice Cream');
insert into product (description) values ('Wine - Zinfandel Rosenblum');
insert into product (description) values ('Pur Source');
insert into product (description) values ('Arrowroot');
insert into product (description) values ('Sour Puss Sour Apple');
insert into product (description) values ('Wine - Sauvignon Blanc Oyster');
insert into product (description) values ('Bread - Roll, Calabrese');
insert into product (description) values ('Cheese - Feta');
insert into product (description) values ('Beer - Blue');
insert into product (description) values ('Glass Clear 8 Oz');
insert into product (description) values ('Tea Leaves - Oolong');
insert into product (description) values ('Asparagus - Frozen');
insert into product (description) values ('Skewers - Bamboo');
insert into product (description) values ('Vodka - Lemon, Absolut');
insert into product (description) values ('Muffin Hinge Container 6');
insert into product (description) values ('Cookie Dough - Double');
insert into product (description) values ('Salmon - Fillets');
insert into product (description) values ('Beef - Shank');
insert into product (description) values ('Haggis');
insert into product (description) values ('Tart Shells - Sweet, 3');
insert into product (description) values ('Higashimaru Usukuchi Soy');
insert into product (description) values ('Squash - Butternut');
insert into product (description) values ('Split Peas - Green, Dry');
insert into product (description) values ('Coffee - Egg Nog Capuccino');
insert into product (description) values ('Beef - Ground, Extra Lean, Fresh');
insert into product (description) values ('Sugar - Icing');
insert into product (description) values ('Apricots - Halves');
insert into product (description) values ('Eggwhite Frozen');
insert into product (description) values ('Teriyaki Sauce');
insert into product (description) values ('Madeira');
insert into product (description) values ('Puff Pastry - Slab');
insert into product (description) values ('Chicken - Leg, Fresh');
insert into product (description) values ('Wine - Red, Lurton Merlot De');
insert into product (description) values ('Okra');
insert into product (description) values ('Bar - Granola Trail Mix Fruit Nut');
insert into product (description) values ('Appetizer - Cheese Bites');
insert into product (description) values ('Appetizer - Smoked Salmon / Dill');
insert into product (description) values ('Truffle - Whole Black Peeled');
insert into product (description) values ('Wine - Wyndham Estate Bin 777');
insert into product (description) values ('Plasticforkblack');
insert into product (description) values ('Chervil - Fresh');
insert into product (description) values ('Schnappes - Peach, Walkers');
insert into product (description) values ('Zucchini - Green');
insert into product (description) values ('Lamb - Shanks');
insert into product (description) values ('Vanilla Beans');
insert into product (description) values ('Ham - Cooked');
insert into product (description) values ('Wine - Tribal Sauvignon');
insert into product (description) values ('Muffin - Blueberry Individual');
insert into product (description) values ('Sauce - Rosee');
insert into product (description) values ('Octopus - Baby, Cleaned');
insert into product (description) values ('Buffalo - Tenderloin');
insert into product (description) values ('Soup - Campbells Tomato Ravioli');
insert into product (description) values ('Veal - Inside');
insert into product (description) values ('Ice Cream - Turtles Stick Bar');
insert into product (description) values ('Cheese - Asiago');
insert into product (description) values ('Nut - Pecan, Pieces');
insert into product (description) values ('Tea - Earl Grey');
insert into product (description) values ('Dried Cranberries');
insert into product (description) values ('Canadian Emmenthal');
insert into product (description) values ('Nantucket - Carrot Orange');
insert into product (description) values ('Veal - Osso Bucco');
insert into product (description) values ('Muffin - Bran Ind Wrpd');
insert into product (description) values ('Wine - Clavet Saint Emilion');
insert into product (description) values ('Soup - Tomato Mush. Florentine');
insert into product (description) values ('Chocolate - Semi Sweet');
insert into product (description) values ('Water, Tap');
insert into product (description) values ('Oven Mitt - 13 Inch');
insert into product (description) values ('Compound - Mocha');
insert into product (description) values ('Cheese - Fontina');
insert into product (description) values ('Sugar - Palm');
insert into product (description) values ('Ginger - Pickled');
insert into product (description) values ('Honey - Liquid');
insert into product (description) values ('Sauerkraut');
insert into product (description) values ('Steel Wool S.o.s');
insert into product (description) values ('Laundry - Bag Cloth');
insert into product (description) values ('Wine - Prosecco Valdobienne');
insert into product (description) values ('Straws - Cocktale');
insert into product (description) values ('Squid - U 5');
insert into product (description) values ('Nutmeg - Ground');
insert into product (description) values ('Lidsoupcont Rp12dn');
insert into product (description) values ('Lychee');
insert into product (description) values ('Beans - Black Bean, Canned');
insert into product (description) values ('Appetizer - Crab And Brie');
insert into product (description) values ('Pan Grease');
insert into product (description) values ('Cookie - Oatmeal');
insert into product (description) values ('Liners - Baking Cups');
insert into product (description) values ('Napkin - Beverge, White 2 - Ply');
insert into product (description) values ('Knife Plastic - White');
insert into product (description) values ('Potatoes - Pei 10 Oz');
insert into product (description) values ('Tarragon - Fresh');
insert into product (description) values ('Beef - Baby, Liver');
insert into product (description) values ('Quail - Whole, Bone - In');
insert into product (description) values ('Beans - French');
insert into product (description) values ('Beef - Ox Tail, Frozen');
insert into product (description) values ('Juice - Mango');
insert into product (description) values ('Limes');
insert into product (description) values ('Bread Base - Toscano');
insert into product (description) values ('Bread - Mini Hamburger Bun');
insert into product (description) values ('Scallops - 20/30');
insert into product (description) values ('Water - Tonic');
insert into product (description) values ('Juice - Happy Planet');
insert into product (description) values ('Easy Off Oven Cleaner');
insert into product (description) values ('Sauce - Hp');
insert into product (description) values ('Pasta - Fettuccine, Dry');
insert into product (description) values ('Pepper - Red, Finger Hot');
insert into product (description) values ('Tomatoes - Heirloom');
insert into product (description) values ('Salt And Pepper Mix - Black');
insert into product (description) values ('Corn - Cream, Canned');
insert into product (description) values ('Crab - Imitation Flakes');
insert into product (description) values ('Mayonnaise - Individual Pkg');
insert into product (description) values ('Rice Paper');
insert into product (description) values ('Coffee - Beans, Whole');
insert into product (description) values ('Artichoke - Bottom, Canned');
insert into product (description) values ('Kellogs All Bran Bars');
insert into product (description) values ('Muffin Chocolate Individual Wrap');
insert into product (description) values ('Quail - Jumbo');
insert into product (description) values ('Yogurt - Plain');
insert into product (description) values ('Vinegar - White');
insert into product (description) values ('Versatainer Nc - 9388');
insert into product (description) values ('Mustard - Dijon');
insert into product (description) values ('Butter Ripple - Phillips');
insert into product (description) values ('Flour - Strong');
insert into product (description) values ('Yoghurt Tubes');
insert into product (description) values ('Wine - Mas Chicet Rose, Vintage');
insert into product (description) values ('Pepper - Gypsy Pepper');
insert into product (description) values ('Bread - Pumpernickel');
insert into product (description) values ('Yogurt - Strawberry, 175 Gr');
insert into product (description) values ('Muffin - Carrot Individual Wrap');
insert into product (description) values ('Nacho Chips');
insert into product (description) values ('Pepper - Red Chili');
insert into product (description) values ('Cup - 6oz, Foam');
insert into product (description) values ('Split Peas - Green, Dry');
insert into product (description) values ('Hagen Daza - Dk Choocolate');
insert into product (description) values ('Corn Meal');
insert into product (description) values ('Long Island Ice Tea');
insert into product (description) values ('Muffin Mix - Carrot');
insert into product (description) values ('Broom - Angled');
insert into product (description) values ('Rum - Spiced, Captain Morgan');
insert into product (description) values ('Tea Peppermint');
insert into product (description) values ('Godiva White Chocolate');
insert into product (description) values ('Lettuce Romaine Chopped');
insert into product (description) values ('Wine - Red, Metus Rose');
insert into product (description) values ('Wine - Puligny Montrachet A.');
insert into product (description) values ('Maintenance Removal Charge');
insert into product (description) values ('Beef - Ox Tail, Frozen');
insert into product (description) values ('Tomatoes - Roma');
insert into product (description) values ('Cheese - Parmesan Cubes');
insert into product (description) values ('Icecream - Dstk Cml And Fdg');
insert into product (description) values ('Lychee - Canned');
insert into product (description) values ('Turkey Tenderloin Frozen');
insert into product (description) values ('Pepper - Sorrano');
insert into product (description) values ('Wine - Delicato Merlot');
insert into product (description) values ('Muffin - Mix - Bran And Maple 15l');
insert into product (description) values ('Butcher Twine 4r');
insert into product (description) values ('Milk - 1%');
insert into product (description) values ('Sauce - Salsa');
insert into product (description) values ('Shichimi Togarashi Peppeers');
insert into product (description) values ('Syrup - Pancake');
insert into product (description) values ('Pastry - Trippleberry Muffin - Mini');
insert into product (description) values ('Shortbread - Cookie Crumbs');
insert into product (description) values ('Oil - Coconut');
insert into product (description) values ('Cocoa Feuilletine');
insert into product (description) values ('Sugar - Sweet N Low, Individual');
insert into product (description) values ('Yeast - Fresh, Fleischman');
insert into product (description) values ('Tart Shells - Sweet, 4');
insert into product (description) values ('Tea - Apple Green Tea');
insert into product (description) values ('Jicama');
insert into product (description) values ('Samosa - Veg');
insert into product (description) values ('Tamarillo');
insert into product (description) values ('Cake Sheet Combo Party Pack');
insert into product (description) values ('Corn Shoots');
insert into product (description) values ('Pastry - Baked Cinnamon Stick');
insert into product (description) values ('Lobster - Baby, Boiled');
insert into product (description) values ('Lamb - Pieces, Diced');
insert into product (description) values ('Sauce - Thousand Island');
insert into product (description) values ('Potatoes - Idaho 100 Count');
insert into product (description) values ('Container - Clear 32 Oz');
insert into product (description) values ('Flavouring - Raspberry');
insert into product (description) values ('French Pastries');
insert into product (description) values ('Sauce - Cranberry');
insert into product (description) values ('Wine - Soave Folonari');
insert into product (description) values ('Dish Towel');
insert into product (description) values ('Venison - Ground');
insert into product (description) values ('Mushroom - Oyster, Fresh');
insert into product (description) values ('Mushroom - King Eryingii');
insert into product (description) values ('Pastry - Lemon Danish - Mini');
insert into product (description) values ('Wine - Conde De Valdemar');
insert into product (description) values ('Sugar - Brown, Individual');
insert into product (description) values ('Longos - Chicken Cordon Bleu');
insert into product (description) values ('Spoon - Soup, Plastic');
insert into product (description) values ('Grenadillo');
insert into product (description) values ('Dawn Professionl Pot And Pan');
insert into product (description) values ('Beer - Fruli');
insert into product (description) values ('Icecream - Dstk Strw Chseck');
insert into product (description) values ('Gatorade - Cool Blue Raspberry');
insert into product (description) values ('Graham Cracker Mix');
insert into product (description) values ('Eel Fresh');
insert into product (description) values ('Lettuce - Boston Bib');
insert into product (description) values ('Cattail Hearts');
insert into product (description) values ('Honey - Comb');
insert into product (description) values ('Huck Towels White');
insert into product (description) values ('Praline Paste');
insert into product (description) values ('Clams - Littleneck, Whole');
insert into product (description) values ('Longos - Cheese Tortellini');
insert into product (description) values ('Bread - Rolls, Corn');
insert into product (description) values ('Bread - Ciabatta Buns');
insert into product (description) values ('Noodles - Steamed Chow Mein');
insert into product (description) values ('Kiwano');
insert into product (description) values ('Skirt - 24 Foot');
insert into product (description) values ('Cheese - Montery Jack');
insert into product (description) values ('Plasticforkblack');
insert into product (description) values ('Shrimp - Prawn');
insert into product (description) values ('Gingerale - Schweppes, 355 Ml');
insert into product (description) values ('Pate Pans Yellow');
insert into product (description) values ('Saskatoon Berries - Frozen');
insert into product (description) values ('Oats Large Flake');
insert into product (description) values ('Kirsch - Schloss');
insert into product (description) values ('Filling - Mince Meat');
insert into product (description) values ('Melon - Honey Dew');
insert into product (description) values ('Juice - V8, Tomato');
insert into product (description) values ('Coffee - Flavoured');
insert into product (description) values ('Tortillas - Flour, 8');
insert into product (description) values ('Soup - Campbells');
insert into product (description) values ('Turnip - White, Organic');
insert into product (description) values ('Bay Leaf Ground');
insert into product (description) values ('Longos - Greek Salad');
insert into product (description) values ('Pork - Suckling Pig');
insert into product (description) values ('Quail - Jumbo Boneless');
insert into product (description) values ('Bread - Kimel Stick Poly');
insert into product (description) values ('Carroway Seed');
insert into product (description) values ('Turkey - Breast, Smoked');
insert into product (description) values ('Chicken - Leg, Boneless');
insert into product (description) values ('Wine - Fume Blanc Fetzer');
insert into product (description) values ('Oil - Sunflower');
insert into product (description) values ('Wine - Red, Black Opal Shiraz');
insert into product (description) values ('Snapple - Mango Maddness');
insert into product (description) values ('Sauce - Alfredo');
insert into product (description) values ('Bread - Granary Small Pull');
insert into product (description) values ('Cheese - Fontina');
insert into product (description) values ('Pepper - White, Ground');
insert into product (description) values ('Capon - Whole');
insert into product (description) values ('Pork - Bones');
insert into product (description) values ('Creamers - 10%');
insert into product (description) values ('Wine - Chianti Classica Docg');
insert into product (description) values ('Steel Wool');
insert into product (description) values ('Foam Dinner Plate');
insert into product (description) values ('Wine - Alicanca Vinho Verde');
insert into product (description) values ('Worcestershire Sauce');
insert into product (description) values ('C - Plus, Orange');
insert into product (description) values ('Cream - 35%');
insert into product (description) values ('Potatoes - Mini Red');
insert into product (description) values ('Garlic - Elephant');
insert into product (description) values ('Bread - Kimel Stick Poly');
insert into product (description) values ('Wine - Zinfandel California 2002');
insert into product (description) values ('Limes');
insert into product (description) values ('Oil - Safflower');
insert into product (description) values ('Butter - Salted');
insert into product (description) values ('Bacardi Mojito');
insert into product (description) values ('Wine - Chateau Timberlay');
insert into product (description) values ('Onions - Vidalia');
insert into product (description) values ('Buttons');
insert into product (description) values ('Wine - Chianti Classico Riserva');
insert into product (description) values ('Beef - Chuck, Boneless');
insert into product (description) values ('Cheese - Cheddar With Claret');
insert into product (description) values ('Oil - Margarine');
insert into product (description) values ('Ecolab Crystal Fusion');
insert into product (description) values ('Scallops 60/80 Iqf');
insert into product (description) values ('Spinach - Baby');
insert into product (description) values ('Garlic - Primerba, Paste');
insert into product (description) values ('Chicken - Base, Ultimate');
insert into product (description) values ('Chips Potato Swt Chilli Sour');
insert into product (description) values ('Piping Jelly - All Colours');
insert into product (description) values ('Fennel');
insert into product (description) values ('Food Colouring - Pink');
insert into product (description) values ('Juice - Orange, Concentrate');
insert into product (description) values ('Cake - Miini Cheesecake Cherry');
insert into product (description) values ('Cheese - Oka');
insert into product (description) values ('Emulsifier');
insert into product (description) values ('Wine - Magnotta, White');
insert into product (description) values ('Sauce - Hollandaise');
insert into product (description) values ('Milk Powder');
insert into product (description) values ('Pepper - Yellow Bell');
insert into product (description) values ('Quail - Eggs, Fresh');
insert into product (description) values ('Beef - Bones, Cut - Up');
insert into product (description) values ('Tandoori Curry Paste');
insert into product (description) values ('Glaze - Apricot');
insert into product (description) values ('Capicola - Hot');
insert into product (description) values ('Bread - Hot Dog Buns');
insert into product (description) values ('Ecolab - Lime - A - Way 4/4 L');
insert into product (description) values ('Laundry - Bag Cloth');
insert into product (description) values ('Eggplant - Asian');
insert into product (description) values ('Wine - Red, Cabernet Merlot');
insert into product (description) values ('True - Vue Containers');
insert into product (description) values ('Fish - Atlantic Salmon, Cold');
insert into product (description) values ('Pasta - Spaghetti, Dry');
insert into product (description) values ('Saskatoon Berries - Frozen');
insert into product (description) values ('Rice Pilaf, Dry,package');
insert into product (description) values ('Juice - Grapefruit, 341 Ml');
insert into product (description) values ('Apple - Fuji');
insert into product (description) values ('Wine - Red, Colio Cabernet');
insert into product (description) values ('Cornflakes');
insert into product (description) values ('Kiwi Gold Zespri');
insert into product (description) values ('Chicken - Bones');
insert into product (description) values ('Beef Ground Medium');
insert into product (description) values ('Apple - Delicious, Red');
insert into product (description) values ('Beans - Kidney, Canned');
insert into product (description) values ('Mustard Prepared');
insert into product (description) values ('Gelatine Leaves - Envelopes');
insert into product (description) values ('Dasheen');
insert into product (description) values ('Beans - Kidney White');
insert into product (description) values ('Wine - Fat Bastard Merlot');
insert into product (description) values ('Salmon Steak - Cohoe 6 Oz');
insert into product (description) values ('Appetizer - Crab And Brie');
insert into product (description) values ('Beef - Top Sirloin');
insert into product (description) values ('Madeira');
insert into product (description) values ('Wine - Rhine Riesling Wolf Blass');
insert into product (description) values ('Table Cloth 62x120 White');
insert into product (description) values ('Sauce - Rosee');
insert into product (description) values ('Oil - Canola');
insert into product (description) values ('Spic And Span All Purpose');
insert into product (description) values ('The Pop Shoppe - Root Beer');
insert into product (description) values ('Tomato - Tricolor Cherry');
insert into product (description) values ('Asparagus - White, Canned');
insert into product (description) values ('Flour - Semolina');
insert into product (description) values ('Milk - Chocolate 500ml');
insert into product (description) values ('Water - Spring 1.5lit');
insert into product (description) values ('Ecolab - Mikroklene 4/4 L');
insert into product (description) values ('Sauerkraut');
insert into product (description) values ('Mustard - Individual Pkg');
insert into product (description) values ('Coffee - Cafe Moreno');
insert into product (description) values ('Sobe - Berry Energy');
insert into product (description) values ('Longos - Greek Salad');
insert into product (description) values ('Compound - Raspberry');
insert into product (description) values ('Squeeze Bottle');
insert into product (description) values ('Crush - Cream Soda');
insert into product (description) values ('Bandage - Fexible 1x3');
insert into product (description) values ('Cornstarch');
insert into product (description) values ('Pepsi, 355 Ml');
insert into product (description) values ('Prunes - Pitted');
insert into product (description) values ('Pastry - Key Limepoppy Seed Tea');
insert into product (description) values ('Nori Sea Weed');
insert into product (description) values ('Star Anise, Whole');
insert into product (description) values ('Cheese - Mozzarella');
insert into product (description) values ('Apple - Northern Spy');
insert into product (description) values ('Nescafe - Frothy French Vanilla');
insert into product (description) values ('Tahini Paste');
insert into product (description) values ('Cloves - Ground');
insert into product (description) values ('Capon - Breast, Wing On');
insert into product (description) values ('Roe - White Fish');
insert into product (description) values ('Beer - Steamwhistle');
insert into product (description) values ('Dawn Professionl Pot And Pan');
insert into product (description) values ('Asparagus - Frozen');
insert into product (description) values ('Melon - Watermelon, Seedless');
insert into product (description) values ('Turkey - Oven Roast Breast');
insert into product (description) values ('Napkin - Beverage 1 Ply');
insert into product (description) values ('Napkin White');
insert into product (description) values ('Pasta - Shells, Medium, Dry');
insert into product (description) values ('Lid - 10,12,16 Oz');
insert into product (description) values ('Noodles - Steamed Chow Mein');
insert into product (description) values ('Dikon');
insert into product (description) values ('Coffee - Flavoured');
insert into product (description) values ('Appetizer - Escargot Puff');
insert into product (description) values ('Chicken - White Meat With Tender');
insert into product (description) values ('Beef - Bones, Cut - Up');
insert into product (description) values ('Lamb - Whole Head Off');
insert into product (description) values ('Sloe Gin - Mcguinness');
insert into product (description) values ('Spinach - Frozen');
insert into product (description) values ('Tequila Rose Cream Liquor');
insert into product (description) values ('Bread - Pita, Mini');
insert into product (description) values ('Ice Cream - Chocolate');
insert into product (description) values ('Wine - Soave Folonari');
insert into product (description) values ('Milk - Buttermilk');
insert into product (description) values ('Butter Sweet');
insert into product (description) values ('Pork Loin Cutlets');
insert into product (description) values ('Mountain Dew');
insert into product (description) values ('Piping Jelly - All Colours');
insert into product (description) values ('Bread - Crumbs, Bulk');
insert into product (description) values ('Veal - Insides Provini');
insert into product (description) values ('Myers Planters Punch');
insert into product (description) values ('Pasta - Orecchiette');
insert into product (description) values ('Alize Gold Passion');
insert into product (description) values ('Butter - Salted, Micro');
insert into product (description) values ('Carbonated Water - White Grape');
insert into product (description) values ('Cheese - Boursin, Garlic / Herbs');
insert into product (description) values ('Pork - Side Ribs');
insert into product (description) values ('Arizona - Green Tea');
insert into product (description) values ('Sansho Powder');
insert into product (description) values ('Quail - Whole, Bone - In');
insert into product (description) values ('Calypso - Strawberry Lemonade');
insert into product (description) values ('Snapple - Mango Maddness');
insert into product (description) values ('Water - Aquafina Vitamin');
insert into product (description) values ('Arizona - Plum Green Tea');
insert into product (description) values ('Cheese - Ermite Bleu');
insert into product (description) values ('Cheese - Shred Cheddar / Mozza');
insert into product (description) values ('Wine - Cousino Macul Antiguas');
insert into product (description) values ('Graham Cracker Mix');
insert into product (description) values ('Cheese - Bakers Cream Cheese');
insert into product (description) values ('Bread - Italian Corn Meal Poly');
insert into product (description) values ('Cattail Hearts');
insert into product (description) values ('Fennel - Seeds');
insert into product (description) values ('Spice - Paprika');
insert into product (description) values ('Oil - Canola');
insert into product (description) values ('Longos - Chicken Curried');
insert into product (description) values ('Tea - English Breakfast');
insert into product (description) values ('Tomatoes - Vine Ripe, Red');
insert into product (description) values ('Parsley - Dried');
insert into product (description) values ('Soup - Campbells - Chicken Noodle');
insert into product (description) values ('Cod - Black Whole Fillet');
insert into product (description) values ('Beef - Cooked, Corned');
insert into product (description) values ('Icecream - Dstk Cml And Fdg');
insert into product (description) values ('Capon - Breast, Wing On');
insert into product (description) values ('Longos - Chicken Wings');
insert into product (description) values ('Wine - White Cab Sauv.on');
insert into product (description) values ('Coffee - Hazelnut Cream');
insert into product (description) values ('Turkey Leg With Drum And Thigh');
insert into product (description) values ('Mix - Cappucino Cocktail');
insert into product (description) values ('Potatoes - Pei 10 Oz');
insert into product (description) values ('Seedlings - Mix, Organic');
insert into product (description) values ('Beef - Bones, Marrow');
insert into product (description) values ('Celery Root');
insert into product (description) values ('Rolled Oats');
insert into product (description) values ('Hickory Smoke, Liquid');
insert into product (description) values ('Straws - Cocktale');
insert into product (description) values ('Soup Knorr Chili With Beans');
insert into product (description) values ('Soup - Boston Clam Chowder');
insert into product (description) values ('Cheese - Cheddar, Mild');
insert into product (description) values ('Tea - Lemon Scented');
insert into product (description) values ('Edible Flower - Mixed');
insert into product (description) values ('Chevere Logs');
insert into product (description) values ('Mints - Striped Red');
insert into product (description) values ('Trout Rainbow Whole');
insert into product (description) values ('Bread - Burger');
insert into product (description) values ('Pepsi - 600ml');
insert into product (description) values ('Broom Handle');
insert into product (description) values ('Lentils - Red, Dry');
insert into product (description) values ('Tea - Lemon Scented');
insert into product (description) values ('Blueberries - Frozen');
insert into product (description) values ('Table Cloth 54x72 Colour');
insert into product (description) values ('Grapes - Black');
insert into product (description) values ('Wine - White, Pinot Grigio');
insert into product (description) values ('Tortillas - Flour, 10');
insert into product (description) values ('Veal - Chops, Split, Frenched');
insert into product (description) values ('Lettuce - Arugula');
insert into product (description) values ('Sugar - Brown, Individual');
insert into product (description) values ('Cheese - Provolone');
insert into product (description) values ('Cheese - Brie Roitelet');
insert into product (description) values ('Wine La Vielle Ferme Cote Du');
insert into product (description) values ('Chocolate - Liqueur Cups With Foil');
insert into product (description) values ('Cleaner - Comet');
insert into product (description) values ('Eggroll');
insert into product (description) values ('Coffee Swiss Choc Almond');
insert into product (description) values ('Sour Puss Sour Apple');
insert into product (description) values ('Wine - Red, Colio Cabernet');
insert into product (description) values ('Pepper - Scotch Bonnet');
insert into product (description) values ('Cabbage - Green');
insert into product (description) values ('Dill - Primerba, Paste');
insert into product (description) values ('Wine - Chenin Blanc K.w.v.');
insert into product (description) values ('Roe - Flying Fish');
insert into product (description) values ('Creme De Banane - Marie');
insert into product (description) values ('Bread - Hamburger Buns');
insert into product (description) values ('Kahlua');
insert into product (description) values ('Glycerine');
insert into product (description) values ('Rice - Basmati');
insert into product (description) values ('Cleaner - Lime Away');
insert into product (description) values ('Pumpkin - Seed');
insert into product (description) values ('Chocolate - Unsweetened');
insert into product (description) values ('Sour Puss Sour Apple');
insert into product (description) values ('Herb Du Provence - Primerba');
insert into product (description) values ('Beans - Black Bean, Canned');
insert into product (description) values ('Cookie Choc');
insert into product (description) values ('Appetizer - Mini Egg Roll, Shrimp');
insert into product (description) values ('Pastry - Cheese Baked Scones');
insert into product (description) values ('Lemonade - Strawberry, 591 Ml');
insert into product (description) values ('Nut - Pine Nuts, Whole');
insert into product (description) values ('Hot Chocolate - Individual');
insert into product (description) values ('Dill Weed - Dry');
insert into product (description) values ('Onions - Pearl');
insert into product (description) values ('Sambuca - Ramazzotti');
insert into product (description) values ('Relish');
insert into product (description) values ('Muffin - Bran Ind Wrpd');
insert into product (description) values ('Bulgar');
insert into product (description) values ('Beef - Tenderloin - Aa');
insert into product (description) values ('Ranchero - Primerba, Paste');
insert into product (description) values ('Trueblue - Blueberry 12x473ml');
insert into product (description) values ('Bar - Sweet And Salty Chocolate');
insert into product (description) values ('Wine - Dubouef Macon - Villages');
insert into product (description) values ('Apple - Macintosh');
insert into product (description) values ('Grapefruit - White');
insert into product (description) values ('Flower - Leather Leaf Fern');
insert into product (description) values ('Oven Mitts - 15 Inch');
insert into product (description) values ('Jameson - Irish Whiskey');
insert into product (description) values ('Lamb - Shoulder, Boneless');
insert into product (description) values ('Oranges - Navel, 72');
insert into product (description) values ('Goulash Seasoning');
insert into product (description) values ('Skirt - 24 Foot');
insert into product (description) values ('Nut - Pecan, Halves');
insert into product (description) values ('Table Cloth 72x144 White');
insert into product (description) values ('Pork - Ham Hocks - Smoked');
insert into product (description) values ('Bar - Sweet And Salty Chocolate');
insert into product (description) values ('Allspice - Jamaican');
insert into product (description) values ('Wine - Balbach Riverside');
insert into product (description) values ('Flower - Commercial Bronze');
insert into product (description) values ('Cookie Dough - Double');
insert into product (description) values ('Apple - Fuji');
insert into product (description) values ('Corn - Mini');
insert into product (description) values ('Beef - Baby, Liver');
insert into product (description) values ('Chocolate - Milk, Callets');
insert into product (description) values ('Pepper - Red Thai');
insert into product (description) values ('Nut - Cashews, Whole, Raw');
insert into product (description) values ('Sauce Tomato Pouch');
insert into product (description) values ('Chives - Fresh');
insert into product (description) values ('Sausage - Breakfast');
insert into product (description) values ('Wine - Red, Cooking');
insert into product (description) values ('Goat - Leg');
insert into product (description) values ('Black Currants');
insert into product (description) values ('Apricots - Halves');
insert into product (description) values ('Pumpkin - Seed');
insert into product (description) values ('Cabbage - Nappa');
insert into product (description) values ('Cake Circle, Paprus');
insert into product (description) values ('Yoplait Drink');
insert into product (description) values ('Berry Brulee');
insert into product (description) values ('Flavouring - Raspberry');
insert into product (description) values ('Bread Fig And Almond');
insert into product (description) values ('Broom Handle');
insert into product (description) values ('Straws - Cocktale');
insert into product (description) values ('Cilantro / Coriander - Fresh');
insert into product (description) values ('Ecolab - Hobart Washarm End Cap');
insert into product (description) values ('Beer - Heinekin');
insert into product (description) values ('Beef - Salted');
insert into product (description) values ('Compound - Passion Fruit');
insert into product (description) values ('Cheese Cloth No 60');
insert into product (description) values ('Beef - Top Butt Aaa');
insert into product (description) values ('Stock - Veal, White');
insert into product (description) values ('Wine - Pinot Grigio Collavini');
insert into product (description) values ('Bar Mix - Pina Colada, 355 Ml');
insert into product (description) values ('Pastry - French Mini Assorted');
insert into product (description) values ('Lettuce - Treviso');
insert into product (description) values ('Lettuce - Arugula');
insert into product (description) values ('Bread Country Roll');
insert into product (description) values ('Mix - Cappucino Cocktail');
insert into product (description) values ('Pernod');
insert into product (description) values ('Quail - Whole, Boneless');
insert into product (description) values ('Nut - Almond, Blanched, Ground');
insert into product (description) values ('Grenadillo');
insert into product (description) values ('Tart Shells - Sweet, 3');
insert into product (description) values ('Wanton Wrap');
insert into product (description) values ('Nori Sea Weed');
insert into product (description) values ('Juice - Apple Cider');
insert into product (description) values ('Chips Potato All Dressed - 43g');
insert into product (description) values ('Oil - Olive, Extra Virgin');
insert into product (description) values ('Peppercorns - Pink');
insert into product (description) values ('Soup - Beef Conomme, Dry');
insert into product (description) values ('Salmon - Atlantic, Skin On');
insert into product (description) values ('Energy Drink - Redbull 355ml');
insert into product (description) values ('Goldschalger');
insert into product (description) values ('Ham - Proscuitto');
insert into product (description) values ('Cream - 18%');
insert into product (description) values ('Wine - Blue Nun Qualitatswein');
insert into product (description) values ('Lid - 10,12,16 Oz');
insert into product (description) values ('Bar - Granola Trail Mix Fruit Nut');
insert into product (description) values ('Sausage - Andouille');
insert into product (description) values ('Flower - Leather Leaf Fern');
insert into product (description) values ('Ice Cream Bar - Hageen Daz To');
insert into product (description) values ('Beans - Fava Fresh');
insert into product (description) values ('Crab - Dungeness, Whole, live');
insert into product (description) values ('Pastry - Raisin Muffin - Mini');
insert into product (description) values ('Lamb - Loin, Trimmed, Boneless');
insert into product (description) values ('Greens Mustard');
insert into product (description) values ('Danishes - Mini Cheese');
insert into product (description) values ('Wine - Touraine Azay - Le - Rideau');
insert into product (description) values ('Soda Water - Club Soda, 355 Ml');
insert into product (description) values ('Glass - Wine, Plastic, Clear 5 Oz');
insert into product (description) values ('Table Cloth 54x54 White');
insert into product (description) values ('Rosemary - Dry');
insert into product (description) values ('Wine - Red, Pinot Noir, Chateau');
insert into product (description) values ('Carbonated Water - Cherry');
insert into product (description) values ('Wine - Harrow Estates, Vidal');
insert into product (description) values ('Grapes - Red');
insert into product (description) values ('Pears - Anjou');
insert into product (description) values ('Potatoes - Peeled');
insert into product (description) values ('Cabbage - Savoy');
insert into product (description) values ('Jolt Cola');
insert into product (description) values ('Pasta - Agnolotti - Butternut');
insert into product (description) values ('Soup - Campbells Chicken');
insert into product (description) values ('Ginger - Pickled');
insert into product (description) values ('Mousse - Banana Chocolate');
insert into product (description) values ('Paper Towel Touchless');
insert into product (description) values ('Oranges - Navel, 72');
insert into product (description) values ('Milk - 2%');
insert into product (description) values ('Hot Chocolate - Individual');
insert into product (description) values ('Beef - Bones, Cut - Up');
insert into product (description) values ('Chilli Paste, Ginger Garlic');
insert into product (description) values ('Cheese Cloth');
insert into product (description) values ('Lotus Rootlets - Canned');
insert into product (description) values ('Energy Drink Red Bull');
insert into product (description) values ('Tuna - Salad Premix');
insert into product (description) values ('Chickhen - Chicken Phyllo');
insert into product (description) values ('Ecolab - Orange Frc, Cleaner');
insert into product (description) values ('Puree - Blackcurrant');
insert into product (description) values ('Salad Dressing');
insert into product (description) values ('Tea - Lemon Green Tea');
insert into product (description) values ('Veal - Round, Eye Of');
insert into product (description) values ('Muffin - Carrot Individual Wrap');
insert into product (description) values ('Bread - Hot Dog Buns');
insert into product (description) values ('Steampan - Foil');
insert into product (description) values ('Juice - Grapefruit, 341 Ml');
insert into product (description) values ('Vodka - Hot, Lnferno');
insert into product (description) values ('Wine - Gewurztraminer Pierre');
insert into product (description) values ('Caviar - Salmon');
insert into product (description) values ('Sugar - Crumb');
insert into product (description) values ('Cheese - Havarti, Salsa');
insert into product (description) values ('Longos - Chicken Caeser Salad');
insert into product (description) values ('Bread - English Muffin');
insert into product (description) values ('Wine - Rubyport');
insert into product (description) values ('Arrowroot');
insert into product (description) values ('Longos - Burritos');
insert into product (description) values ('Beer - Blue Light');
insert into product (description) values ('Chicken - Whole Roasting');
insert into product (description) values ('Tart Shells - Barquettes, Savory');
insert into product (description) values ('Flour - Buckwheat, Dark');
insert into product (description) values ('Pastry - Cheese Baked Scones');
insert into product (description) values ('Sugar Thermometer');
insert into product (description) values ('Five Alive Citrus');
insert into product (description) values ('Cup - Translucent 7 Oz Clear');
insert into product (description) values ('Spice - Onion Powder Granulated');
insert into product (description) values ('Versatainer Nc - 888');
insert into product (description) values ('Pails With Lids');
insert into product (description) values ('Flower - Commercial Bronze');
insert into product (description) values ('Bols Melon Liqueur');
insert into product (description) values ('Pastry - Apple Large');
insert into product (description) values ('Piping - Bags Quizna');
insert into product (description) values ('Crab - Back Fin Meat, Canned');
insert into product (description) values ('Daikon Radish');
insert into product (description) values ('Wine - Niagara Peninsula Vqa');
insert into product (description) values ('Bagel - 12 Grain Preslice');
insert into product (description) values ('Sambuca Cream');
insert into product (description) values ('Flower - Daisies');
insert into product (description) values ('Veal - Insides, Grains');
insert into product (description) values ('Cinnamon Rolls');
insert into product (description) values ('Contreau');
insert into product (description) values ('Beer - Rickards Red');
insert into product (description) values ('Crush - Orange, 355ml');
insert into product (description) values ('Bread - Flat Bread');
insert into product (description) values ('Juice - Orange, Concentrate');
insert into product (description) values ('Shrimp - 16/20, Peeled Deviened');
insert into product (description) values ('Sauce - Soya, Dark');
insert into product (description) values ('Cheese - Mozzarella, Shredded');
insert into product (description) values ('Tarragon - Fresh');
insert into product (description) values ('Spoon - Soup, Plastic');
insert into product (description) values ('Bacardi Mojito');
insert into product (description) values ('Capicola - Hot');
insert into product (description) values ('Shiro Miso');
insert into product (description) values ('Cheese - Pont Couvert');
insert into product (description) values ('Pasta - Orecchiette');
insert into product (description) values ('Nantucket - 518ml');
insert into product (description) values ('Beef - Tenderloin - Aa');
insert into product (description) values ('Bag Stand');
insert into product (description) values ('Sour Puss Raspberry');
insert into product (description) values ('Tea - Apple Green Tea');
insert into product (description) values ('Calypso - Black Cherry Lemonade');
insert into product (description) values ('Honey - Lavender');
insert into product (description) values ('Tuna - Fresh');
insert into product (description) values ('Pasta - Gnocchi, Potato');
insert into product (description) values ('Spic And Span All Purpose');
insert into product (description) values ('Saskatoon Berries - Frozen');
insert into product (description) values ('Scotch - Queen Anne');
insert into product (description) values ('Mix - Cocktail Strawberry Daiquiri');
insert into product (description) values ('Gingerale - Diet - Schweppes');
insert into product (description) values ('Soup - Campbells, Beef Barley');
insert into product (description) values ('Chicken - Base, Ultimate');
insert into product (description) values ('Eel Fresh');
insert into product (description) values ('Rosemary - Fresh');
insert into product (description) values ('Garbage Bag - Clear');
insert into product (description) values ('Sugar - Individual Portions');
insert into product (description) values ('Energy Drink');
insert into product (description) values ('Cheese - Taleggio D.o.p.');
insert into product (description) values ('Currants');
insert into product (description) values ('Hand Towel');
insert into product (description) values ('Triple Sec - Mcguinness');
insert into product (description) values ('Bulgar');
insert into product (description) values ('Salmon - Atlantic, Fresh, Whole');
insert into product (description) values ('Lamb - Ground');
insert into product (description) values ('Onions - Red');
insert into product (description) values ('Lamb Rack Frenched Australian');
insert into product (description) values ('Sugar - Monocystal / Rock');
insert into product (description) values ('Squash - Butternut');
insert into product (description) values ('Bread - Rosemary Focaccia');
insert into product (description) values ('Wine - Ej Gallo Sierra Valley');
insert into product (description) values ('Wine - White, Riesling, Semi - Dry');
insert into product (description) values ('Cheese - Ermite Bleu');
insert into product (description) values ('Broom Handle');
insert into product (description) values ('Chocolate - Mi - Amere Semi');
insert into product (description) values ('Piping Jelly - All Colours');
insert into product (description) values ('Hersey Shakes');
insert into product (description) values ('Chinese Foods - Cantonese');
insert into product (description) values ('Bread - Dark Rye, Loaf');
insert into product (description) values ('Soup - Campbells, Beef Barley');
insert into product (description) values ('Chips - Doritos');
insert into product (description) values ('Coconut - Shredded, Sweet');
insert into product (description) values ('Mussels - Cultivated');
insert into product (description) values ('Chevril');
insert into product (description) values ('Cake - Sheet Strawberry');
insert into product (description) values ('Glaze - Apricot');
insert into product (description) values ('Longos - Chicken Cordon Bleu');
